#!/usr/bin/env bash

keys_csv=$(find . -iname '*_accessKeys.csv' -type f -maxdepth 1 | head -n 1)
if [[ ! -f "$keys_csv" ]]; then
  echo "Could not find an AWS '*_accessKeys.csv' file at the root of the project"
  exit 1
fi

export AWS_REGION="eu-central-1"
export AWS_ACCESS_KEY_ID="$(cat "$keys_csv" | tail -n 1 | awk -F , '{ print $1 }' | tr -d '[:space:]' | tr -d '\r')"
export AWS_SECRET_ACCESS_KEY="$(cat "$keys_csv" | tail -n 1 | awk -F , '{ print $2 }' | tr -d '[:space:]' | tr -d '\r')"