---
- name: Determine NVM version
  shell: |
    source ~/.nvm/nvm.sh
    nvm --version
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: __var__
  changed_when: no

- name: Save NVM version
  when: __var__.stdout | regex_search('\\d+\\.\\d+\\.\\d+')
  set_fact:
    NVM_VERSION: "{{ __var__.stdout }}"

- name: Install NVM
  when: NVM_VERSION is not defined
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  register: __var__
  changed_when: "'already installed' not in __var__.stdout"

- name: Determine NVM version
  shell: |
    source ~/.nvm/nvm.sh
    nvm --version
  args:
    executable: /bin/bash
  register: __var__
  changed_when: no

- name: Install the preferred Node versions
  shell: |
    source ~/.nvm/nvm.sh
    nvm install {{ item }}
    nvm alias default {{ item }}
  args:
    executable: /bin/bash
  register: __var__
  changed_when: "'already installed' not in __var__.stderr"
  with_items: "{{ Dev.PREFERRED_NODE_VERSIONS }}"